import type { Club } from "./types";

export const CLUBS: Club[] = [
  {
    id: "archery",
    name: "Archery Club",
    category: "Other",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/archery-club",
    img: "/images/SportClubs/archery.jpg",
    desc: "No experience needed — rec & competition tracks with USA Archery-certified coaches.",
    tags: ["No Tryout", "Equipment Provided", "Rec & Comp"],
    tryout: {
      kind: "info",
      schedule: "Thursdays 4:00 – 6:00 PM",
      location: "Jogging Path / Campus Archery Range",
      cost: "Semester membership fee — see club page",
      notes: "No prior experience or equipment needed. Compound bows not permitted on campus.",
    },
  },
  {
    id: "badminton",
    name: "Badminton Club",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/badminton-club",
    img: "/images/SportClubs/badminton.jpg",
    desc: "All-levels sessions with drills, singles & doubles ladders, and tournament prep.",
    tags: ["All Levels", "Tournaments", "Singles & Doubles"],
    tryout: { kind: "form" },
  },
  {
    id: "baseball",
    name: "Baseball Club",
    category: "Field",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/baseball-club",
    img: "/images/SportClubs/baseball.jpg",
    desc: "Student-run club baseball with league play, travel games, and skill development.",
    tags: ["League Play", "Travel", "Competitive"],
    tryout: { kind: "form" },
  },
  {
    id: "boxing",
    name: "Boxing Club",
    category: "Martial Arts",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/boxing-club",
    img: "/images/SportClubs/boxing.jpg",
    desc: "Technique, conditioning, and controlled sparring — safety-first culture.",
    tags: ["Safety First", "Conditioning", "Intercollegiate"],
    tryout: { kind: "form", notes: "Wraps and gloves provided for tryout where available." },
  },
  {
    id: "bjj",
    name: "Brazilian Jiu-Jitsu",
    category: "Martial Arts",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/brazilian-jiu-jitsu-club",
    img: "/images/SportClubs/BJJ.jpg",
    desc: "Grappling instruction with drilling, positional sparring, and tournament prep.",
    tags: ["Grappling", "All Levels", "Tournament Prep"],
    tryout: { kind: "form" },
  },
  {
    id: "chess",
    name: "Chess Club",
    category: "Strategy",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/chess-club",
    img: "/images/SportClubs/chess.jpg",
    desc: "Casual and rated play, lessons, and collegiate team competitions.",
    tags: ["Casual & Rated", "Collegiate Team", "Lessons"],
    tryout: { kind: "form" },
  },
  {
    id: "cheer",
    name: "CSUN Cheer",
    category: "Dance",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/cheer-club",
    img: "/images/SportClubs/cheer.jpg",
    desc: "Game-day spirit, stunts, and performance with regular team practices.",
    tags: ["Performance", "Stunts", "Game Day"],
    tryout: { kind: "form", notes: "Possible uniform/dues required — details confirmed at tryout." },
  },
  {
    id: "dance",
    name: "CSUN Dance Club",
    category: "Dance",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/dance-club",
    img: "/images/SportClubs/dance.jpg",
    desc: "Team choreography in multiple styles with performance opportunities.",
    tags: ["Multi-Style", "Performance", "All Levels"],
    tryout: { kind: "form" },
  },
  {
    id: "esports",
    name: "Esports",
    category: "Strategy",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/esports",
    img: "/images/SportClubs/esports.jpg",
    desc: "Valorant, LoL, OW2 and more — coached practice, scrims, and league play.",
    tags: ["Multiple Titles", "Coached", "League Play"],
    tryout: {
      kind: "info",
      schedule: "Title-specific windows — check Discord & club page",
      location: "Games Room / Online (Discord lobbies)",
      cost: "None / TBD",
      notes: "Bring CSUN ID for in-person. Check Discord for active tryout lobbies.",
    },
  },
  {
    id: "fasmode",
    name: "Fasmode Dance Crew",
    category: "Dance",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/fasmode-dance-crew",
    img: "/images/SportClubs/dance.jpg",
    desc: "Student hip-hop dance crew focused on choreography and campus showcases.",
    tags: ["Hip-Hop", "Choreography", "Showcase"],
    tryout: { kind: "form" },
  },
  {
    id: "streetdance",
    name: "Northridge Street Dancers",
    category: "Dance",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/northridge-street-dancers",
    img: "/images/SportClubs/streetdance.jpg",
    desc: "Open-session street styles — breaking, popping, locking — workshops and showcases.",
    tags: ["Street Styles", "Open Sessions", "All Levels"],
    tryout: { kind: "form" },
  },
  {
    id: "hockey",
    name: "Ice Hockey Club",
    category: "Other",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/ice-hockey-club",
    img: "/images/SportClubs/hockey.jpg",
    desc: "ACHA club hockey with structured practices, film, and a competitive schedule.",
    tags: ["ACHA", "Team Travel", "Competitive"],
    tryout: { kind: "form", notes: "Ice fees and equipment costs apply — confirm on the club page." },
  },
  {
    id: "mensbbball",
    name: "Men's Basketball",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/mens-basketball-club-0",
    img: "/images/SportClubs/menbasketball.jpg",
    desc: "Club basketball with team practices, systems work, and collegiate competition.",
    tags: ["Competitive", "Systems", "Club League"],
    tryout: { kind: "form" },
  },
  {
    id: "mensrugby",
    name: "Men's Rugby",
    category: "Field",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/mens-rugby",
    img: "/images/SportClubs/menrugby.jpg",
    desc: "Competitive 15s/7s rugby with fitness, fundamentals, and regional league fixtures.",
    tags: ["15s & 7s", "Regional League", "Fitness"],
    tryout: { kind: "form" },
  },
  {
    id: "mensvball",
    name: "Men's Volleyball",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/mens-volleyball-club",
    img: "/images/SportClubs/menvolleyball.jpg",
    desc: "Indoor volleyball training with team systems, positional work, and tournament play.",
    tags: ["Indoor", "Tournament", "Team Systems"],
    tryout: { kind: "form" },
  },
  {
    id: "menssoccer",
    name: "Men's Soccer",
    category: "Field",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/mens-soccer-club",
    img: "/images/SportClubs/mensoccer.jpg",
    desc: "Coached training sessions, friendlies, and league matches throughout the term.",
    tags: ["League Play", "Coached", "Travel"],
    tryout: { kind: "form" },
  },
  {
    id: "salsa",
    name: "Salsa Libre",
    category: "Dance",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/salsa-libre-club",
    img: "/images/SportClubs/salsalibre.jpg",
    desc: "Latin dance community — salsa, bachata, cumbia — classes, socials, performances.",
    tags: ["Latin Dance", "Social", "All Levels"],
    tryout: { kind: "form" },
  },
  {
    id: "swim",
    name: "Swim Club",
    category: "Water",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/swim",
    img: "/images/SportClubs/swim.jpg",
    desc: "Structured workouts, stroke technique coaching, and optional collegiate meets.",
    tags: ["Structured Workouts", "Technique", "Meets"],
    tryout: { kind: "form" },
  },
  {
    id: "tabletennis",
    name: "Table Tennis Club",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/table-tennis-club",
    img: "/images/SportClubs/tabletennis.jpg",
    desc: "Singles and doubles ladders, skill drills, and intercollegiate competition.",
    tags: ["All Levels", "Ladders", "Intercollegiate"],
    tryout: { kind: "form" },
  },
  {
    id: "tennis",
    name: "Tennis Club",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/tennis-club",
    img: "/images/SportClubs/tennis.jpg",
    desc: "Challenge ladders, team practice drills, and club matches against regional schools.",
    tags: ["All Levels", "Ladders", "Travel"],
    tryout: { kind: "form" },
  },
  {
    id: "waterpolo",
    name: "Water Polo Club",
    category: "Water",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/water-polo-club",
    img: "/images/SportClubs/waterpolo.jpg",
    desc: "Tactical practices, conditioning sets, and tournament travel all semester.",
    tags: ["Competitive", "Conditioning", "Tournaments"],
    tryout: { kind: "form" },
  },
  {
    id: "weightlift",
    name: "Weightlifting Club",
    category: "Fitness",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/weightlifting-club",
    img: "/images/SportClubs/weightlifting.jpg",
    desc: "Olympic and powerlifting with coached technique and optional meet prep.",
    tags: ["Olympic Lifting", "Powerlifting", "Coached"],
    tryout: { kind: "form" },
  },
  {
    id: "womensbbball",
    name: "Women's Basketball",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/womens-basketball",
    img: "/images/SportClubs/womenbasketball.jpg",
    desc: "Women's club basketball with system work, scrimmages, and collegiate competition.",
    tags: ["Competitive", "Systems", "Club League"],
    tryout: { kind: "form" },
  },
  {
    id: "womenslax",
    name: "Women's Lacrosse",
    category: "Field",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/womens-lacrosse-club",
    img: "/images/SportClubs/womenlacrosse.jpg",
    desc: "Stick skills, offensive/defensive sets, conditioning, and league play.",
    tags: ["League Play", "Skill Dev", "Supportive"],
    tryout: { kind: "form" },
  },
  {
    id: "womensrugby",
    name: "Women's Rugby",
    category: "Field",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/womens-rugby-club",
    img: "/images/SportClubs/womenrugby.jpg",
    desc: "Competitive women's rugby — safe contact, fitness, and regional fixtures.",
    tags: ["Safe Contact", "Beginner Friendly", "Competitive"],
    tryout: { kind: "form" },
  },
  {
    id: "womenssoccer",
    name: "Women's Soccer",
    category: "Field",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/womens-soccer-club",
    img: "/images/SportClubs/womensoccer.jpg",
    desc: "Coached tactical training, friendly fixtures, and competitive league matches.",
    tags: ["Coached", "League Play", "Friendlies"],
    tryout: { kind: "form" },
  },
  {
    id: "womensvball",
    name: "Women's Volleyball",
    category: "Court",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/womens-volleyball-club",
    img: "/images/SportClubs/womenvolleyball.jpg",
    desc: "Technical positional training, team systems, and active tournament competition.",
    tags: ["Indoor", "Tournament", "Technical"],
    tryout: { kind: "form" },
  },
  {
    id: "wrestling",
    name: "Wrestling Club",
    category: "Martial Arts",
    href: "https://www.csun.edu/as/departments/sport-clubs/available-sports/wrestling-club",
    img: "/images/SportClubs/wrestling.jpg",
    desc: "Folkstyle and freestyle fundamentals, live wrestling, and strength conditioning.",
    tags: ["Folkstyle & Freestyle", "Conditioning", "Competition"],
    tryout: { kind: "form" },
  },
];
