//workout deck data
import type { MuscleGroup, WorkoutCard } from "./WorkoutDeck";

// All valid muscle groups
export const ALL_GROUPS: MuscleGroup[] = [
  "Chest",
  "Back",
  "Legs",
  "Shoulders",
  "Arms",
  "Core",
  "Full Body",
  "Cardio",
];

// Main deck data
export const WORKOUT_DECK: WorkoutCard[] = [
  // -------------------- CHEST --------------------
  {
    id: "bp-1",
    name: "Barbell Bench Press",
    description: "Heavy strength focus on mid-chest.",
    group: "Chest",
    image: "/cards/benchpressCard.png",
    sets: "5",
    focuses: ["Chest", "Shoulders", "Arms"],
  },
  {
    id: "bp-2",
    name: "Incline Dumbbell Press",
    description: "Upper chest emphasis with full range.",
    group: "Chest",
    image: "/cards/inclinePressCard.png",
    sets: "4",
    focuses: ["Chest", "Shoulders"],
  },
  {
    id: "bp-3",
    name: "Cable Fly",
    description: "Big chest squeeze and controlled return.",
    group: "Chest",
    image: "/cards/cableFlyCard.png",
    sets: "3",
    focuses: ["Chest"],
  },
  {
    id: "bp-4",
    name: "Push Ups",
    description: "Bodyweight classic, strict form.",
    group: "Chest",
    image: "/cards/pushupsCard.png",
    sets: "3",
    focuses: ["Chest", "Core", "Arms"],
  },
  {
    id: "bp-5",
    name: "Dumbbell Bench Press",
    description: "Neutral grip dumbbells for joint-friendly pressing.",
    group: "Chest",
    image: "/cards/dbBenchCard.png",
    sets: "4",
    focuses: ["Chest", "Arms"],
  },
  {
    id: "bp-6",
    name: "Decline Barbell Press",
    description: "Lower chest focus with controlled tempo.",
    group: "Chest",
    image: "/cards/declinePressCard.png",
    sets: "4",
    focuses: ["Chest"],
  },
  {
    id: "bp-7",
    name: "Machine Chest Press",
    description: "Stable press to push close to failure safely.",
    group: "Chest",
    image: "/cards/machinePressCard.png",
    sets: "3",
    focuses: ["Chest", "Shoulders"],
  },
  {
    id: "bp-8",
    name: "Pec Deck Fly",
    description: "Chest isolation with constant tension.",
    group: "Chest",
    image: "/cards/pecDeckCard.png",
    sets: "3",
    focuses: ["Chest"],
  },
  {
    id: "bp-9",
    name: "Deficit Push Ups",
    description: "Hands elevated on blocks for deeper stretch.",
    group: "Chest",
    image: "/cards/deficitPushupCard.png",
    sets: "3",
    focuses: ["Chest", "Shoulders", "Core"],
  },
  {
    id: "bp-10",
    name: "Close Grip Push Ups",
    description: "Narrow hand placement for inner chest and triceps.",
    group: "Chest",
    image: "/cards/closeGripPushupCard.png",
    sets: "3",
    focuses: ["Chest", "Arms"],
  },

  // -------------------- BACK --------------------
  {
    id: "bk-1",
    name: "Pull Ups",
    description: "Wide grip, full extension at the bottom.",
    group: "Back",
    image: "/cards/pullupsCard.png",
    sets: "4",
    focuses: ["Back", "Arms"],
  },
  {
    id: "bk-2",
    name: "Barbell Row",
    description: "Strict hip hinge with strong row.",
    group: "Back",
    image: "/cards/barbellRowCard.png",
    sets: "4",
    focuses: ["Back"],
  },
  {
    id: "bk-3",
    name: "Lat Pulldown",
    description: "Full stretch at top, squeeze at chest.",
    group: "Back",
    image: "/cards/latPulldownCard.png",
    sets: "3",
    focuses: ["Back"],
  },
  {
    id: "bk-4",
    name: "Seated Cable Row",
    description: "Neutral grip, no leaning back.",
    group: "Back",
    image: "/cards/cableRowCard.png",
    sets: "3",
    focuses: ["Back"],
  },
  {
    id: "bk-5",
    name: "Single Arm Dumbbell Row",
    description: "One side at a time with full stretch.",
    group: "Back",
    image: "/cards/dbRowCard.png",
    sets: "3",
    focuses: ["Back", "Arms"],
  },
  {
    id: "bk-6",
    name: "Chest Supported Row",
    description: "Row with chest on bench to remove momentum.",
    group: "Back",
    image: "/cards/chestSupportedRowCard.png",
    sets: "3",
    focuses: ["Back"],
  },
  {
    id: "bk-7",
    name: "Straight Arm Pulldown",
    description: "Lat isolation with straight elbows.",
    group: "Back",
    image: "/cards/straightArmPulldownCard.png",
    sets: "3",
    focuses: ["Back"],
  },
  {
    id: "bk-8",
    name: "Inverted Row",
    description: "Bodyweight row using a bar or TRX.",
    group: "Back",
    image: "/cards/invertedRowCard.png",
    sets: "3",
    focuses: ["Back", "Core"],
  },
  {
    id: "bk-9",
    name: "Rack Pull",
    description: "Partial deadlift from pins for upper back.",
    group: "Back",
    image: "/cards/rackPullCard.png",
    sets: "4",
    focuses: ["Back"],
  },
  {
    id: "bk-10",
    name: "Meadows Row",
    description: "Landmine row variation for upper lats.",
    group: "Back",
    image: "/cards/meadowsRowCard.png",
    sets: "3",
    focuses: ["Back"],
  },

  // -------------------- LEGS --------------------
  {
    id: "lg-1",
    name: "Back Squat",
    description: "Barbell squat, full depth as mobility allows.",
    group: "Legs",
    image: "/cards/squatCard.png",
    sets: "5",
    focuses: ["Legs", "Core"],
  },
  {
    id: "lg-2",
    name: "Romanian Deadlift",
    description: "Slow eccentric to target hamstrings.",
    group: "Legs",
    image: "/cards/rdlCard.png",
    sets: "4",
    focuses: ["Legs"],
  },
  {
    id: "lg-3",
    name: "Walking Lunges",
    description: "Alternating lunges for distance or steps.",
    group: "Legs",
    image: "/cards/lungesCard.png",
    sets: "3",
    focuses: ["Legs", "Core"],
  },
  {
    id: "lg-4",
    name: "Leg Press",
    description: "Controlled reps without locking knees.",
    group: "Legs",
    image: "/cards/legPressCard.png",
    sets: "4",
    focuses: ["Legs"],
  },
  {
    id: "lg-5",
    name: "Leg Extension",
    description: "Quad isolation with controlled squeeze.",
    group: "Legs",
    image: "/cards/legExtensionCard.png",
    sets: "3",
    focuses: ["Legs"],
  },
  {
    id: "lg-6",
    name: "Leg Curl",
    description: "Hamstring curl, focus on full contraction.",
    group: "Legs",
    image: "/cards/legCurlCard.png",
    sets: "3",
    focuses: ["Legs"],
  },
  {
    id: "lg-7",
    name: "Goblet Squat",
    description: "Dumbbell front-loaded squat, upright torso.",
    group: "Legs",
    image: "/cards/gobletSquatCard.png",
    sets: "3",
    focuses: ["Legs", "Core"],
  },
  {
    id: "lg-8",
    name: "Bulgarian Split Squat",
    description: "Rear foot elevated for single-leg quad focus.",
    group: "Legs",
    image: "/cards/bssCard.png",
    sets: "3",
    focuses: ["Legs", "Core"],
  },
  {
    id: "lg-9",
    name: "Calf Raises",
    description: "Standing or machine calf work, full stretch.",
    group: "Legs",
    image: "/cards/calfRaiseCard.png",
    sets: "4",
    focuses: ["Legs"],
  },
  {
    id: "lg-10",
    name: "Front Squat",
    description: "Barbell front rack squat, upright chest.",
    group: "Legs",
    image: "/cards/frontSquatCard.png",
    sets: "4",
    focuses: ["Legs", "Core"],
  },

  // -------------------- SHOULDERS --------------------
  {
    id: "sh-1",
    name: "Overhead Press",
    description: "Standing strict barbell press.",
    group: "Shoulders",
    image: "/cards/ohpCard.png",
    sets: "5",
    focuses: ["Shoulders", "Arms", "Core"],
  },
  {
    id: "sh-2",
    name: "Lateral Raises",
    description: "Dumbbell laterals with slow tempo.",
    group: "Shoulders",
    image: "/cards/lateralRaiseCard.png",
    sets: "4",
    focuses: ["Shoulders"],
  },
  {
    id: "sh-3",
    name: "Seated Dumbbell Press",
    description: "Press in a stable seated position.",
    group: "Shoulders",
    image: "/cards/dbShoulderPressCard.png",
    sets: "4",
    focuses: ["Shoulders", "Arms"],
  },
  {
    id: "sh-4",
    name: "Face Pulls",
    description: "Cable pulls to face for rear delts and traps.",
    group: "Shoulders",
    image: "/cards/facePullCard.png",
    sets: "3",
    focuses: ["Shoulders", "Back"],
  },
  {
    id: "sh-5",
    name: "Rear Delt Fly",
    description: "Reverse fly on machine or with dumbbells.",
    group: "Shoulders",
    image: "/cards/rearDeltFlyCard.png",
    sets: "3",
    focuses: ["Shoulders"],
  },
  {
    id: "sh-6",
    name: "Front Raise",
    description: "Dumbbell raises in front to shoulder height.",
    group: "Shoulders",
    image: "/cards/frontRaiseCard.png",
    sets: "3",
    focuses: ["Shoulders"],
  },
  {
    id: "sh-7",
    name: "Arnold Press",
    description: "Rotational dumbbell press variation.",
    group: "Shoulders",
    image: "/cards/arnoldPressCard.png",
    sets: "4",
    focuses: ["Shoulders", "Arms"],
  },
  {
    id: "sh-8",
    name: "Machine Shoulder Press",
    description: "Guided press for safe heavy work.",
    group: "Shoulders",
    image: "/cards/machineShoulderPressCard.png",
    sets: "3",
    focuses: ["Shoulders"],
  },
  {
    id: "sh-9",
    name: "Cable Lateral Raise",
    description: "Cable variation for constant tension.",
    group: "Shoulders",
    image: "/cards/cableLateralCard.png",
    sets: "3",
    focuses: ["Shoulders"],
  },
  {
    id: "sh-10",
    name: "Y Raise",
    description: "Light dumbbells raised into a Y shape.",
    group: "Shoulders",
    image: "/cards/yRaiseCard.png",
    sets: "3",
    focuses: ["Shoulders", "Back"],
  },

  // -------------------- ARMS --------------------
  {
    id: "ar-1",
    name: "Barbell Curl",
    description: "Full range curls, no swinging.",
    group: "Arms",
    image: "/cards/curlCard.png",
    sets: "4",
    focuses: ["Arms"],
  },
  {
    id: "ar-2",
    name: "Tricep Rope Pushdown",
    description: "Squeeze at lockout each rep.",
    group: "Arms",
    image: "/cards/tricepPushdownCard.png",
    sets: "4",
    focuses: ["Arms"],
  },
  {
    id: "ar-3",
    name: "Hammer Curl",
    description: "Neutral grip curls for brachialis.",
    group: "Arms",
    image: "/cards/hammerCurlCard.png",
    sets: "3",
    focuses: ["Arms"],
  },
  {
    id: "ar-4",
    name: "Skull Crushers",
    description: "EZ-bar tricep extensions on bench.",
    group: "Arms",
    image: "/cards/skullCrusherCard.png",
    sets: "3",
    focuses: ["Arms"],
  },
  {
    id: "ar-5",
    name: "Preacher Curl",
    description: "Strict curl with arm support.",
    group: "Arms",
    image: "/cards/preacherCurlCard.png",
    sets: "3",
    focuses: ["Arms"],
  },
  {
    id: "ar-6",
    name: "Cable Curl",
    description: "Constant tension curls on cable stack.",
    group: "Arms",
    image: "/cards/cableCurlCard.png",
    sets: "3",
    focuses: ["Arms"],
  },
  {
    id: "ar-7",
    name: "Overhead Tricep Extension",
    description: "Dumbbell or cable overhead for long head.",
    group: "Arms",
    image: "/cards/ohTricepExtCard.png",
    sets: "3",
    focuses: ["Arms"],
  },
  {
    id: "ar-8",
    name: "Close Grip Bench Press",
    description: "Bench variation for tricep emphasis.",
    group: "Arms",
    image: "/cards/closeGripBenchCard.png",
    sets: "4",
    focuses: ["Arms", "Chest"],
  },
  {
    id: "ar-9",
    name: "Dip (Assisted or Bodyweight)",
    description: "Upright torso to bias triceps.",
    group: "Arms",
    image: "/cards/tricepDipCard.png",
    sets: "3",
    focuses: ["Arms", "Chest"],
  },
  {
    id: "ar-10",
    name: "Concentration Curl",
    description: "Seated, one arm at a time with tight form.",
    group: "Arms",
    image: "/cards/concentrationCurlCard.png",
    sets: "3",
    focuses: ["Arms"],
  },

  // -------------------- CORE --------------------
  {
    id: "cr-1",
    name: "Plank",
    description: "Hold strong, no sagging hips.",
    group: "Core",
    image: "/cards/plankCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-2",
    name: "Hanging Leg Raises",
    description: "Slow controlled leg lift, no swinging.",
    group: "Core",
    image: "/cards/legRaiseCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-3",
    name: "Cable Crunch",
    description: "Kneeling crunch with rope attachment.",
    group: "Core",
    image: "/cards/cableCrunchCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-4",
    name: "Russian Twists",
    description: "Rotational work with plate or dumbbell.",
    group: "Core",
    image: "/cards/russianTwistCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-5",
    name: "Dead Bug",
    description: "Controlled opposite arm/leg extension.",
    group: "Core",
    image: "/cards/deadBugCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-6",
    name: "Ab Wheel Rollout",
    description: "Roll forward to challenging but safe depth.",
    group: "Core",
    image: "/cards/abWheelCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-7",
    name: "Side Plank",
    description: "Hold on elbow or hand, straight line body.",
    group: "Core",
    image: "/cards/sidePlankCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-8",
    name: "Reverse Crunch",
    description: "Hips curl up off pad slowly.",
    group: "Core",
    image: "/cards/reverseCrunchCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-9",
    name: "Toe Touches",
    description: "Reach toward toes with short controlled crunch.",
    group: "Core",
    image: "/cards/toeTouchCard.png",
    sets: "3",
    focuses: ["Core"],
  },
  {
    id: "cr-10",
    name: "Bird Dog",
    description: "Opposite arm/leg reach keeping hips level.",
    group: "Core",
    image: "/cards/birdDogCard.png",
    sets: "3",
    focuses: ["Core"],
  },

  // -------------------- FULL BODY --------------------
  {
    id: "fb-1",
    name: "Kettlebell Swing",
    description: "Explosive hip drive, neutral spine.",
    group: "Full Body",
    image: "/cards/kbSwingCard.png",
    sets: "4",
    focuses: ["Full Body", "Legs", "Core"],
  },
  {
    id: "fb-2",
    name: "Burpees",
    description: "Conditioning finisher from floor to jump.",
    group: "Full Body",
    image: "/cards/burpeeCard.png",
    sets: "3",
    focuses: ["Full Body", "Cardio"],
  },
  {
    id: "fb-3",
    name: "Thrusters",
    description: "Front squat into overhead press combo.",
    group: "Full Body",
    image: "/cards/thrusterCard.png",
    sets: "3",
    focuses: ["Full Body", "Legs", "Shoulders"],
  },
  {
    id: "fb-4",
    name: "Man Makers",
    description: "Push up, row, and clean-press chain.",
    group: "Full Body",
    image: "/cards/manMakerCard.png",
    sets: "3",
    focuses: ["Full Body", "Core"],
  },
  {
    id: "fb-5",
    name: "Clean and Press",
    description: "Power clean into overhead press.",
    group: "Full Body",
    image: "/cards/cleanPressCard.png",
    sets: "4",
    focuses: ["Full Body"],
  },
  {
    id: "fb-6",
    name: "Farmer's Carry",
    description: "Heavy dumbbells walked for distance.",
    group: "Full Body",
    image: "/cards/farmerCarryCard.png",
    sets: "4",
    focuses: ["Full Body", "Core"],
  },
  {
    id: "fb-7",
    name: "Bear Crawl",
    description: "Crawl forward with hips low and core tight.",
    group: "Full Body",
    image: "/cards/bearCrawlCard.png",
    sets: "3",
    focuses: ["Full Body", "Core"],
  },
  {
    id: "fb-8",
    name: "Devil's Press",
    description: "Burpee into dual dumbbell snatch.",
    group: "Full Body",
    image: "/cards/devilsPressCard.png",
    sets: "3",
    focuses: ["Full Body", "Cardio"],
  },
  {
    id: "fb-9",
    name: "Wall Ball Shots",
    description: "Squat and throw medicine ball to target.",
    group: "Full Body",
    image: "/cards/wallBallCard.png",
    sets: "3",
    focuses: ["Full Body", "Legs", "Cardio"],
  },
  {
    id: "fb-10",
    name: "Sandbag Shouldering",
    description: "Lift sandbag from floor to shoulder repeatedly.",
    group: "Full Body",
    image: "/cards/sandbagShoulderCard.png",
    sets: "3",
    focuses: ["Full Body", "Legs", "Core"],
  },

  // -------------------- CARDIO --------------------
  {
    id: "cd-1",
    name: "Treadmill Intervals",
    description: "30s fast / 60s walk style intervals.",
    group: "Cardio",
    image: "/cards/treadmillCard.png",
    sets: "10",
    focuses: ["Cardio"],
  },
  {
    id: "cd-2",
    name: "Bike Sprints",
    description: "20s all-out / 100s easy spin.",
    group: "Cardio",
    image: "/cards/bikeCard.png",
    sets: "8",
    focuses: ["Cardio"],
  },
  {
    id: "cd-3",
    name: "Rowing Machine Intervals",
    description: "Hard 250m row with easy recovery.",
    group: "Cardio",
    image: "/cards/rowerCard.png",
    sets: "8",
    focuses: ["Cardio"],
  },
  {
    id: "cd-4",
    name: "Stair Climber",
    description: "Steady state climb at moderate pace.",
    group: "Cardio",
    image: "/cards/stairClimberCard.png",
    sets: "1",
    focuses: ["Cardio"],
  },
  {
    id: "cd-5",
    name: "Elliptical Intervals",
    description: "Increase resistance for short bursts.",
    group: "Cardio",
    image: "/cards/ellipticalCard.png",
    sets: "6",
    focuses: ["Cardio"],
  },
  {
    id: "cd-6",
    name: "Outdoor Run",
    description: "Easy to moderate paced jog.",
    group: "Cardio",
    image: "/cards/runCard.png",
    sets: "1",
    focuses: ["Cardio"],
  },
  {
    id: "cd-7",
    name: "Jump Rope",
    description: "Continuous rope skipping for time.",
    group: "Cardio",
    image: "/cards/jumpRopeCard.png",
    sets: "5",
    focuses: ["Cardio"],
  },
  {
    id: "cd-8",
    name: "Sled Push",
    description: "Heavy sled pushed for short distance.",
    group: "Cardio",
    image: "/cards/sledPushCard.png",
    sets: "6",
    focuses: ["Cardio", "Legs"],
  },
  {
    id: "cd-9",
    name: "Battle Ropes",
    description: "High intensity rope slams and waves.",
    group: "Cardio",
    image: "/cards/battleRopeCard.png",
    sets: "6",
    focuses: ["Cardio", "Arms"],
  },
  {
    id: "cd-10",
    name: "Shuttle Runs",
    description: "Short sprint repeats between cones.",
    group: "Cardio",
    image: "/cards/shuttleRunCard.png",
    sets: "8",
    focuses: ["Cardio"],
  },
];
